[package]
edition = "2021"
name = "ensure_no_std"
version = "0.0.0"
publish = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
composable-allocators = "0.1.1"
exit-no-std = "0.1.0"
panicking = { version = "0.3.1", default-features = false, features = ["abort"] }
tuifw-screen = { path = "../screen" }
tuifw-window = { path = ".." }
